services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=examtimetabling'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
#  docker run -d --name postgres -e POSTGRES_DB=examtimetabling -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -p 5432:5432 postgres:latest
